### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop 

### ISSUE THREAD

**Issue by Darealtube** [Darealtube/japhil-project#5]
I do not know why, but at home.tsx, it shows an error that it must have a unique "key" prop. 

I tried adding a key prop to the <Grid item> Component, but it did not work...

Here's the error:

`Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <WithStyles(ForwardRef(CardContent))>. See https://reactjs.org/link/warning-keys for more information.      
    at WithStyles(ForwardRef(Chip)) (D:\react\japhil-project\node_modules\@material-ui\styles\withStyles\withStyles.js:67:31)
    at Home (D:\react\japhil-project\.next\server\pages\home.js:4882:3)
    at MyApp (D:\react\japhil-project\.next\server\pages\_app.js:121:3)
    at StylesProvider (D:\react\japhil-project\node_modules\@material-ui\styles\StylesProvider\StylesProvider.js:57:24)
    at AppContainer (D:\react\japhil-project\node_modules\next\dist\next-server\server\render.js:25:748)`

**Comment by Darealtube** [comment]
This isn't a major issue, and I've easily solved it by adding the Index (from the map function) as a value to the key prop.
